sudo: required
services:
  - docker

before_install:
  - docker build -t shaileshb02/docker-basic -f Dockerfile .

script:
  - docker run shaileshb02/docker-basic npm run test
 
deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-basic"
  env: "Dockerbasic-env"
  bucket_name: "elasticbeanstalk-ap-south-1-281262011230"
  bucket_path: "docker-basic"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY