# .dev indicates that this file is only used for development purpose.

FROM node:alpine AS builder

WORKDIR '/app'

ENV CI=true

COPY package.json .
RUN npm install

COPY . .

RUN npm run build

FROM nginx
EXPOSE 80
COPY --from=builder /app/build /usr/share/nginx/html